### ISSUE TITLE
Moves are disappearing

### ISSUE THREAD

**Issue by sphaso** [neagle/gokibitz#103]
Quite literally!
Unfortunately I don't have the steps to reproduce, but just to keep you on the lookout.
This is the game: https://gokibitz.com/kifu/4JTw6I6r
The original SGF I uploaded has 66 moves, and I remember commenting (Game comments, not "user" comments) them, editing the comments etc.     
I started to notice that some game comments were shifting from one move to another. I log out, come back a few hours later, and the game now has 64 moves! I refresh the page, click "last" and now it's 63 moves.
Proof? Take a look at this screenshot: BenKyo, symeof and myself commented on move 64 before it disappeared.
![screenshot from 2015-06-07 23-02-29](https://cloud.githubusercontent.com/assets/4958220/8026092/14c2017e-0d6a-11e5-8351-cad89f75d1c3.png)

I remember reading their comments and adding mine at move 64 before it disappeared.
This is the original SGF: https://www.dropbox.com/s/fwmzihp7lmeg0bv/musuko-nekochan.sgf?dl=0
Welp.

**Comment by neagle** [comment]
Let me check this out: thanks for giving such complete information!

**Comment by sphaso** [comment]
Thanks to you! 
I have an hunch: I might (or not) have used a tilde ~ character in a comment. However, the SGF I uploaded was void of any comment, so if a comment screwed up the parser it was entirely on GoKibitz side.
Does MongoDB keep revisions like CouchDB? if so, we might have a way to figure out what happened and find a reproducible case.

**Comment by neagle** [comment]
Yeah, I might not be able to blame shift on this one. :wink: I was coming to a similar conclusion. I had a number of bugs on the roll-out of the game comment editing feature, so it's not inconceivable that I missed some point of fragility here.

To be honest, I was worried about the fragility of editing SGFs directly: sometimes I wonder if I should have just broken out all the properties of an SGF file on upload, rather than trying to preserve them as SGFs.

As to MongoDB revisions, I don't know, actually: this is my first MongoDB project. I'll investigate.

**Comment by neagle** [comment]
Oh, and tildes shouldn't be a problem :frowning: I just tested them on a few comments on my local version, and they seem fine. Right now I can't trigger any kind of problem with comments... some kind of parsing error triggered by some kind of character or other is the most likely culprit. And if that's the case, it's most likely to be something I'm escaping, like a square bracket, quotation mark, or backslash.

**Comment by sphaso** [comment]
Oh wait,
> And if that's the case, it's most likely to be something I'm escaping, like a square bracket, quotation mark, or backslash.

By quotation mark, do you mean `"` ? Because I'm pretty sure I used them in a few instances.

**Comment by neagle** [comment]
Yep, but those all seem to come through just fine. Is there any chance you used a backslash? I think I can reproduce the problem with that. I'm starting to suspect this is actually another instance of the same bug we had last time, with a backslash right before a final closing bracket.

**Comment by sphaso** [comment]
It's very possible I've used a backslash!

**Comment by neagle** [comment]
I think I've fixed this issue: it is, indeed, all about having a backslash before a closing bracket. In this case both my own code and WGo's were working together in an impressive way to break in this condition, which I didn't have in any of my test cases. It's still only on my dev box, but I'll try to get it committed and launched this evening.

**Comment by sphaso** [comment]
Great stuff! Out of curiosity, how was it different from `:\` ?

**Comment by neagle** [comment]
Well, the original error was with WGo breaking when it tried to parse `:\`. The other error you discovered was my own [smartgame](https://github.com/neagle/smartgame) module breaking when it tried to write comments to the SGF that contained `:\` for essentially the same regex-related reason. Every time it tried to write that comment, it didn't properly recognize the closing bracket, so it kept gobbling up text till it hit the _next_ ending bracket, thereby devouring a single move every time such an edit was attempted.

This should now be fixed on live. I also tried to restore your SGF for you, along with the game comments I could: https://gokibitz.com/kifu/4JTw6I6r?path=66

I appreciate your help in finding bugs and giving me great details on the problem.

**Comment by sphaso** [comment]
Brilliant! thanks :)
