### ISSUE TITLE
Does editing a comment with @notifications cause multiple notifications to be sent?

### ISSUE THREAD

**Issue by neagle** [neagle/gokibitz#114]
![2015-12-29 at 3 06 pm](https://cloud.githubusercontent.com/assets/176993/12041262/c351b1c0-ae3d-11e5-9024-e7421a0b8040.png)

**Comment by levelonedev** [comment]
Yes it could be a little more intelligent though and only send ones to people who were added though, by comparing the previous comment to the new one.

I sent new notifications because they could have added more names in their edit.
