### ISSUE TITLE
Entering blank comment makes comment window unusable.

### ISSUE THREAD

**Issue by Aeium** [neagle/gokibitz#122]
Repro:
1. Go to a move in a go record.
2. Click comment window.
3. Hit enter to submit a blank comment.
4. Observe comment window becomes grey and unresponsive.

It's fixed by reloading the page, but you need to do that before you can actually post a comment from there.

**Comment by neagle** [comment]
Reproduced! That's an impressively basic one to have existed for so long. We'll try to get this taken care of soon. Thanks for pointing it out!
