### ISSUE TITLE
Feature Request: vertical timeline on side of board

### ISSUE THREAD

**Issue by peepotronic** [neagle/gokibitz#127]
A timeline of each move played displayed like a vertical ruler on the side of the board. Moves with discussion associated with them are highlighted and can be clicked on to go to that move.

**Comment by neagle** [comment]
It's an interesting idea, but a little complicated. Keeping it around as a possible idea for the future.

**Comment by peepotronic** [comment]
Yes, I tend to agree. I don't think it's something that is really necessary on one hand, and on the other hand it's kind of hard to implement...
