### ISSUE TITLE
Feature Request: link to another move from the comments

### ISSUE THREAD

**Issue by peepotronic** [neagle/gokibitz#128]
Provide a simple way to link to another move or variation within a comment. A regex that will match something like "move 32" with any kind of punctuation in between the word move and the number of the move. Variations might be tricker though and perhaps should be turned into a separate issue once basic links to moves are done?

**Comment by neagle** [comment]
![move-linker](https://cloud.githubusercontent.com/assets/176993/21747553/fa21e090-d537-11e6-8e51-312b93ac2ae8.gif)

This was a lovely suggestion: sorry it took so long to get to it. I launched this tonight and really like the way it works. Thank you!

**Comment by peepotronic** [comment]
Thanks! I'm glad you got it working!!
