### ISSUE TITLE
Feature Request: Allow variations with only one move in them

### ISSUE THREAD

**Issue by RauliRuohonen** [neagle/gokibitz#129]
Currently you can either show a single point like D16 (shows a cross) or multiple moves like bD16 F17 (shows a variation), but you can't show a single-move variation like bD16. It would be an improvement to allow bD16 and show it on the board immediately on mouse over like D16, but with the stone properly placed and current move removed if it's an alternative move. Animating a single move wouldn't be particularly useful, and showing it immediately on mouse over ensures that "bD16" is strictly better than just "D16" when you really are talking about a black move instead of a board point or a stone already on the board.

Especially for alternative moves it's clearer if the current move is removed and a new one is placed at an alternative location to show how the board position differs instead of having to imagine it. Even in real life when people comment on games they typically take the stone and place it elsewhere to show the difference visually instead of just pointing with a finger. I expect one would commonly use this by moving the mouse over the "bD16" comment, then away, then back again repeatedly to assess the difference.

**Comment by popz73** [comment]
I'd love to see this one too, looks to be simple enough for someone to contribute - maybe even myself!

**Comment by neagle** [comment]
I'd definitely welcome a contribution on this one, popz73. 😄
