### ISSUE TITLE
Add like button to comments

### ISSUE THREAD

**Issue by neagle** [neagle/gokibitz#13]
how about a "like" button for a good review and then a small list of top reviewers. This may encourage participation

https://twitter.com/endriagopr/status/554653199895117825

**Comment by neagle** [comment]
This was half completed by https://github.com/neagle/gokibitz/commit/81ec558fa3bbe5e87485ea9a364bd9d0514a41a3, which added comment stars & notifications. I'll also be creating ways to view users' stars to complete the rest of it.

**Comment by levelonedev** [comment]
This can be closed since you can view their star count on their user page.
