### ISSUE TITLE
Feature Request _ disable comments

### ISSUE THREAD

**Issue by Eyecatcher00** [neagle/gokibitz#133]
after seeing today a upload where the uploader asked for "please no comments" ... i was wondering if it wouldn`t be useful to forbid other users to comment... gokibitz looks beatiful so not everyone is uploading because they actual want social discussion... (i do only upload at GoK. to do so... but some people have other needs)

**Comment by neagle** [comment]
Huh: we essentially have a no-comments mode, it's the "public" checkbox. But it's possible the user might have missed it.

When your games are set to public (ie, with the public checkbox off), only you or people you send the link to will ever see it.

**Comment by Eyecatcher00** [comment]
ah, cool … yeah i know the public checkbox … yeah, but in that case i feel he wanted to share the already in sgf comments to the community :) 
greetings

**Comment by neagle** [comment]
Ah, it's [alireynes' game](https://gokibitz.com/kifu/EyuUpLvw-). Yeah, they posted [an earlier game](https://gokibitz.com/kifu/NkXXvDVUW?path=1&comment=5788597694d1755d4aeb8733) where tuerda made a comment about it being a bit strange.

I think you're right that alireynes just wanted to share a game that's not intended for comment. In this case, I don't think alireynes means they need to turn off comments, so much as they're trying to follow my advice to include a note saying that a game review isn't necessary. :) Anyway, they're doing something kind of interesting in using GoKibitz a slightly different way. For the moment, I don't think we need a new feature, but it's very interesting to see different uses pop up.

**Comment by Eyecatcher00** [comment]
yeah, i fully agree :) 

 at the moment a „please no review“ note feels a bit strange, i agree with tuerda … but at the same time i see, like you, that it is good that people using gokibitz differently now…
