### ISSUE TITLE
SGF download broken for some games, possibly due to Chinese characters

### ISSUE THREAD

**Issue by mikedesu** [neagle/gokibitz#137]
[https://gokibitz.com/api/kifu/Sy_4KxSrg/sgf](https://gokibitz.com/api/kifu/Sy_4KxSrg/sgf)

SGFs fail to load with or without comments.

502 Bad Gateway
nginx/1.10.0 (Ubuntu)

**Comment by neagle** [comment]
Thanks for the bug report: I can confirm the issue. This could be a problem with my SGF parser related to the characters in the file. I'll look into it soon.

**Comment by neagle** [comment]
Is there any chance you have a copy of the original SGF that was used to upload the game? I'm trying to debug this issue locally.

**Comment by aniljava** [comment]
Added .txt at the end to allow upload.

https://gokibitz.com/kifu/rJXteo5rx

[[谜团]vs[Master]2017010458178378.sgf.txt](https://github.com/neagle/gokibitz/files/685257/vs.Master.2017010458178378.sgf.txt)

**Comment by neagle** [comment]
Looks like the problem was the non-ASCII characters in the `content-disposition` header for the filename. Turned out to be a pretty easy fix. Thanks for reporting this @mikedesu, and thanks @aniljava for providing the SGF that let me quickly diagnose the issue: I appreciate it!
