### ISSUE TITLE
Edited profile information does not seem to be stored

### ISSUE THREAD

**Issue by Hofsmo** [neagle/gokibitz#140]
Hi,
I have tried multiple times to update my profile information. If I save my changes and don't leave my profile page I can push edit and I see my changes. However, if I navigate somewhere else on the page my changes disappear.

**Comment by neagle** [comment]
I just confirmed the bug. Sorry for the trouble, @Hofsmo, and thank you for reporting the issue. I'll try to get this fixed later tonight.

**Comment by Hofsmo** [comment]
@neagle Many thanks for the quick reply. Btw. the bug has not really been bugging me too much I just wanted to let you know. And thanks for creating gokibitz it has been very useful for my go studies.

**Comment by neagle** [comment]
Thanks for saying so, @Hofsmo! 😄 

I'm glad the bug wasn't much of an issue, but I hate for things like that to persist, so your taking the time to report it was a big help. This should be taken care of on live now. Let me know if you have any other issues.
