### ISSUE TITLE
download sgf broken?

### ISSUE THREAD

**Issue by peepotronic** [neagle/gokibitz#146]
I can't seem to click on the download sgf or share drop downs. Nothing happens when I click on them. Same behaviour for both firefox and chrome on windows 10 64 bit desktop.

**Comment by peepotronic** [comment]
Thanks!!

**Comment by neagle** [comment]
Yeesh: too many items that I let get broken in the recent upgrade I did of UI Bootstrap. Big thanks for reporting this! It should be fixed now.
