### ISSUE TITLE
cross at a given position staying in the goban

### ISSUE THREAD

**Issue by git-oca** [neagle/gokibitz#15]
Hi, if I place the mouse over a position in a comment, like "C10" for example, an X appear in the goban showing that position, this is great ... but then, if I use the cursor key '->' to go to the next move, the marked 'X' position is not cleared on the goban.

**Comment by neagle** [comment]
Ha: I noticed that, too, a little while ago. Thanks for marking it as an issue to that I have to get it taken care of!
