### ISSUE TITLE
Bug: Putting "Move xx" into a comment doesn't get the right link

### ISSUE THREAD

**Issue by GreenAsJade** [neagle/gokibitz#159]
I see that "Move xx" automagically translates into a link to the move xx.

Unforunately, it doesn't reliably work.

I had to change all the "Move xx" other than "Move 57" into "Turn xx" in the comment at https://gokibitz.com/kifu/Sk2iKSlkZ?path=63&comment=5903293e579aff1b70d5b20d

because no matter what xx I put in there, the link always points to Move 57!   

(Move 57 was the first one I created in that comment, as it happens - the other ones were edited in afterwards)

**Comment by neagle** [comment]
Ah, interesting. That bug makes sense. I'll try to get it fixed this week.

--
Nate Eagle

**Comment by neagle** [comment]
Should be good to go! Thanks for reporting the bug, @GreenAsJade!
