### ISSUE TITLE
Feature Request - displaying sequences

### ISSUE THREAD

**Issue by git-oca** [neagle/gokibitz#16]
Reading this comment by Yossaria (http://gokibitz.com/kifu/Xyz44v8qE?path=14) :

"Yossarian 2 hours ago
This seems like the wrong direction to me - I would be happy to play out a relatively simple joseki - like R14, R16, Q14, O17, Q10 - to try and build a moyo."

That make me think that would be fine to be able to see sequences in the goban
a bit like it works with individual move that shows an 'X' but in this case that would place stones with numbering starting at 1 to display the varaiation. that last playexd move should certainly also be removed... (showing game position -1)

I think that would be simplier than implementing a full "gobook" format, and still very usefull... 

here is a quick picture of what that would look like 

![capture](https://cloud.githubusercontent.com/assets/10583590/5792702/690322e8-9f26-11e4-8093-acc1a6a4b4c7.PNG)

**Comment by neagle** [comment]
I actually think this is a _really_ good idea. It doesn't mean we can't do fuller go-book style notation later on or even some of the more involved stuff I was thinking of, but this has the significant advantage of being very straightforward to implement. Back to you soon!

**Comment by neagle** [comment]
Thanks again for your suggestion, oca. You really helped make this happen. Let me know what you think of the implementation: I'm always open to feedback.

**Comment by git-oca** [comment]
That's looks allready great ! but think that the first move in the sequence should replace the last played move, So move 1, R14  should be white here i think, like in the picture in the prévoies message

**Comment by neagle** [comment]
You can already do that by specifying the color of the first move, but I
think your suggestion to change the default makes sense

--
Nate Eagle

On Jan 20, 2015, at 5:14 PM, git-oca <notifications@github.com> wrote:

That's looks allready great ! but think that the first move in the sequence
should replace the last played move, So move 1, R14 should be white here i
think, like in the picture in the prévoies message

—
Reply to this email directly or view it on GitHub
<https://github.com/neagle/gokibitz/issues/16#issuecomment-70745359>.

**Comment by neagle** [comment]
I've updated the default to be the color which last played, so the
sequence's first move replaces the last game move.

--
Nate Eagle

On Jan 20, 2015, at 5:14 PM, git-oca <notifications@github.com> wrote:

That's looks allready great ! but think that the first move in the sequence
should replace the last played move, So move 1, R14 should be white here i
think, like in the picture in the prévoies message

—
Reply to this email directly or view it on GitHub
<https://github.com/neagle/gokibitz/issues/16#issuecomment-70745359>.

**Comment by git-oca** [comment]
That's so great ! just a quick little one, if you look at that comment : http://gokibitz.com/kifu/Xyz44v8qE?path=14, 

The initial move is not replaced, I suppose this is due to the "displaySequence" function in sgfLabel,js, where the variable "firstMove" should now be initialized with "lastMove.c"

Maybe something like that : (but not checked as I have a few errors right now while building the last version, see below...)

var lastMove = $scope.player.kifuReader.node.move;
var displaySequence = lastMove.c;

if (attributes.firstMove) {
	firstMove = (attributes.firstMove === 'W') ? -1 : 1;
}

if (lastMove.c === firstMove) {
	$scope.player.board.removeObjectsAt(lastMove.x, lastMove.y);
}


Problem while building :
>gulp
...
C:\Users\oca\Desktop\my\gokibitz\server\utils\parseLabels.js
  line 7  col 123  Line is too long.
...
1 problem
[08:05:53] gulp-notify: [Compile Error] Error: Cannot find module 'angular-file-
upload' from 'C:\Users\oca\Desktop\my\gokibitz\client\src\js'
...
[08:05:54] gulp-notify: [Compile Error] Error: Cannot find module 'dom-delegate'
 from 'C:\Users\oca\Desktop\my\gokibitz\client\src\js\directives'

**Comment by git-oca** [comment]
there is also a small bug when we go to the next move and the sequence is still active, then the priginal stone is not displayed anymore...

step to reproduce : 

1) go to http://gokibitz.com/kifu/QkgtBEmV?path=34
2) click on the sequence  W O1, N3, M3, O3, M2, M4.
3) click on the next button to go to move 35 (here you can see that the original white stone at M5 is not present)
4) click on the back button to go back to move 34 

this will show : 

![capture](https://cloud.githubusercontent.com/assets/10583590/5835595/d7b2cd74-a16a-11e4-93ee-ed506e13570e.jpg)

**Comment by neagle** [comment]
Sorry about the build errors: I forgot to push a couple items that I hurriedly fixed on my server to make it build, which was bad manners on my part.

Thanks for checking up on this: you're awesome! It's amazing what things you can manage to forget to double-check, even when you think you're running through all the possible interactions. I fixed those bugs this morning, thanks to you.

**Comment by git-oca** [comment]
That't perfect ! thanks I really like this feature !

**Comment by git-oca** [comment]
oups... found a new one ;) ...

if you go here : http://gokibitz.com/kifu/m1gwesI9V?path=6

1) click on O17 P17 variation
2) use the back button to go moves 5,4,3,2,1,0, the stone at O16 doesn't disapear...

**Comment by neagle** [comment]
You're awesome. It didn't even occur to me to check that edge case. Okay: this is the first thing I'll fix tonight.

**Comment by git-oca** [comment]
A quick new one ;)  this sequence doen't appear on the goban when I click on it
http://gokibitz.com/kifu/XJi08D7r?path=25

**Comment by neagle** [comment]
Huh! I wonder what's happening there. I'll check it out in a bit.

--
Nate Eagle

On Jan 22, 2015, at 12:18 PM, git-oca <notifications@github.com> wrote:

A quick new one ;) this sequence doen't appear on the goban when I click on
it
http://gokibitz.com/kifu/XJi08D7r?path=25

—
Reply to this email directly or view it on GitHub
<https://github.com/neagle/gokibitz/issues/16#issuecomment-71058607>.

**Comment by neagle** [comment]
I don't feel as embarrassed about this one: that was a pretty creative way to break the parser. Good job finding it! Another gold star for @git-oca.
