### ISSUE TITLE
Feature Request: can our OGS username link back to OGS, like the KGS one

### ISSUE THREAD

**Issue by GreenAsJade** [neagle/gokibitz#160]
... because OGS is the way of the future ;)

It would be fine to ask me what my OGS profile link is, if you can't work it out.

(Maybe we should ask OGS to implement a username-based route to the user's page!  Seriously!)

**Comment by neagle** [comment]
If OGS implemented a username-based route, I'd definitely be happy to add it, but until then, I'd rather not go to extra lengths.

> ... because OGS is the way of the future ;)

😁  OGS is awesome, but I think it's in everyone's best interest to have multiple great go servers to choose from. Here's to a future with OGS, KGS, and more!

**Comment by apetresc** [comment]
It looks like OGS [has added username-based routing!](https://github.com/online-go/online-go.com/commit/e99463b029f2d50c21e69395940ea9d4409a1e44). Anoek said it would go live on prod with the Automatch update later this week.

**Comment by apetresc** [comment]
It's live now, by the way: https://online-go.com/user/xhu98

**Comment by neagle** [comment]
Thanks for keeping me updated! This is live now. :)
