### ISSUE TITLE
Feature Request: Can we rotate the board, and switch the colours?

### ISSUE THREAD

**Issue by GreenAsJade** [neagle/gokibitz#162]
Now that I am experimenting with using gokibitz to discuss "situations" like joseki or other, I've realised it would be nice to be able to rotate/mirror and switch colors the view, so you can easily see how it applies to a game situation.

This would have to change the render of board references in the comments too ;)

**Comment by neagle** [comment]
This feature would take some work. I'd potentially accept it as a project from a motivated contributor, but it's not something I'm going to take on. 😁
