### ISSUE TITLE
Bug: SGF "game name" not honoured

### ISSUE THREAD

**Issue by GreenAsJade** [neagle/gokibitz#165]
After a bit of experimenting, I've discovered that kifu are named "{black player name} vs {white player name}" no matter what.

I think that if the SGF has a "game name" field then this should be the name of the kifu.

This will allow kifu to get meaningful names, like "The Lee Seedol Ladder Game" or "3-3 4-4 invasion joseki"

**Comment by neagle** [comment]
http://www.red-bean.com/sgf/properties.html#GN

> Provides a name for the game. The name is used to easily find games within a collection. The name should therefore contain some helpful information for identifying the game. 'GameName' could also be used as the file-name, if a collection is split into single files.

This suggestion makes sense. Shouldn't be too hard to implement, either. I'll see if I can get to it soon.

**Comment by GreenAsJade** [comment]
This SGF file had a title in the SGF, but is still called "Black vs White" upon upload:

https://gokibitz.com/kifu/r1D2JhJz-

**Comment by neagle** [comment]
The names displayed at the top are the names of the white and black players, which come from the [PW](http://www.red-bean.com/sgf/properties.html#PW) and [PB](http://www.red-bean.com/sgf/properties.html#PB) properties, respectively. The SGF you uploaded lists those as "White" and "Black". The [GN](http://www.red-bean.com/sgf/properties.html#GN) property only affects the filename of the SGF when you download it.

**Comment by neagle** [comment]
Re-reading your original comment, it looks like I misunderstood your original request. You wanted the GN property to affect the header that displays above games in GoKibitz, whereas I thought you were referring to the filename of the SGF when it gets downloaded, as per the spec.

I don't want to display game names at the top—I'd rather keep that information consistent and purely show player names. You should feel free to use the [GC](http://www.red-bean.com/sgf/properties.html#GC) property (game comment) to add additional context that will show up in the left-hand bar, as shown on this link: https://gokibitz.com/kifu/rkI-2_yM-

**Comment by neagle** [comment]
I would be willing to add "Game Name" above where "Game Comment" is displayed in the Game Info panel, though, if that would be helpful.

**Comment by GreenAsJade** [comment]
Ahah!   I think the most important place for the SGF game name to appear is where the kifu is listed.

For example, I don't think it will be very helpful for me to have a load of "white vs black" kifu with different scenarios in each.   Much better for me to have a list like

4-4 3-3 Invasion Joseki
3 space 3rd Line invasion

etc

Similarly, a kifu named "The Lee Sedol Ladder Game" would be more meaningful than "Lee Sedol 
 vs Hong Chang Sik" (since there have been more than one game between those two - how do you know if it's the one you're looking for?)

**Comment by popz73** [comment]
It seems that you're using the platform for local position studies, where
the title is definitely more relevant, as it isn't an actual game.

Be aware though that it is not the main usage of the platform, and for full
games, there are only a few cases meaningful titles like "Lee Sedol Ladder
Game" - it's not a representative example. For "at a glance" kifu info, the
information that is always relevant is still the name of the players and
their rank, I wouldn't change that. I think that the game title should be
considered as an addition to that, not a replacement.

**Comment by GreenAsJade** [comment]
I agree that positional analysis does not appear to be the core business of gokibitz - it's an interesting experiment/extension.   But talking about positions is a clear need the same way that talking about games.

The spirit of my suggestion is one that especially suits positional discussion, but adds value for game discussion as wel.   I agree that the game title should be an addition, not a replacement.
