### ISSUE TITLE
Should reviews/reviewers be incentivized?

### ISSUE THREAD

**Issue by jonschoning** [neagle/gokibitz#167]
Since reviews cost time & effort, some kind of feature to "reward" especially helpful reviews may be appropriate.  May also require feature to distinguish especially helpful reviews or especially active reviewers

**Comment by neagle** [comment]
What did you have in mind?

--
Nate Eagle

**Comment by jonschoning** [comment]
not sure.  Since I don't fully understand the culture, perhaps the most dedicated users don't need it, but I wonder if it would help bring back occasional users.  There are some obvious ideas here e.g. some kind of points system (karma, whatever you want to call it).  This indicates who was been doing a lot of work on the site and displays to others who's reviews have been helpful.  

On the other hand, the ranks already provide some kind of indication of quality, but 1) ranks may not be accurate 2) some highly ranked players may be better/ more helpful at reviewing than others, which would be great to be recognized for.  

The idea around having "points" is recognition/status + indication of quality.  

A whole sub-topic is how to generate "points".  This could happen any number of ways, but are less of concern exactly how this occurs.  perhaps one idea is to add a small check/thumbs up next to user comments that when checked/upvoted, points are added to the commenter.  this indicates that the comment was helpful.

**Comment by popz73** [comment]
are you already aware of the stars you can give to reviewer's comments,
that accumulate on their profile info? It looks to be exactly what you were
looking for

**Comment by jonschoning** [comment]
Ah, the stars are the same thing. I guess I didn't understand a 'star' was an 'upvote'.  Sometimes 'star' means 'save this for later' or 'bookmark' in other systems.  maybe there just just be a message for new users explaining how the UI works.
