### ISSUE TITLE
Development Setup not working on windows (8)

### ISSUE THREAD

**Issue by git-oca** [neagle/gokibitz#17]
Hi, just wanna let you know that I tried the Development Setup procedure,
and I still got the following error on windows :

![capture](https://cloud.githubusercontent.com/assets/10583590/5793060/afc4f8aa-9f35-11e4-961a-53b262d29342.PNG)

So I just copy WGO.js stuff manually and that do the trick... but just wanna let you know

**Comment by neagle** [comment]
Did you try running `npm install`? I just changed the way WGo.js was included in the project from being brought in as a submodule (go to hell git submodules) to being listed as a dependency in `package.json`. That _should_ solve things.

Sorry about the changes, here, but this is still a pretty young project. :)

**Comment by git-oca** [comment]
got it... on my windows plateform these two files :

- gokibitz\client\src\scss\lib\_gokibitz.scss 
- gokibitz\client\src\js\lib\wgo

are... text files.... not symbolic link... so I deleted them and recreated the symbolic link, with the dos command mklink like this :

[code]
C:\Users\oca\Desktop\my\gokibitz\client\src\scss\lib>mklink _gokibitz.scss C:\Us
ers\oca\Desktop\my\gokibitz\node_modules\wgo.js\gokibitz\src\scss\gokibitz.css
Impossible de créer un fichier déjà existant.

C:\Users\oca\Desktop\my\gokibitz\client\src\scss\lib>mklink _gokibitz.scss C:\Us
ers\oca\Desktop\my\gokibitz\node_modules\wgo.js\gokibitz\src\scss\gokibitz.css
Lien symbolique créé pour _gokibitz.scss <<===>> C:\Users\oca\Desktop\my\gokibit
z\node_modules\wgo.js\gokibitz\src\scss\gokibitz.css

C:\Users\oca\Desktop\my\gokibitz\client\src\scss\lib>
[/code]

And this part is working.

I still have one error : 

[13:01:02] [gulp-sass] c:\Users\oca\Desktop\my\gokibitz\client\src\scss/rules/mo
dules/_notifications.scss:56: error: unbound variable $font-body

the full gulp result is this one now :

[13:01:00] Using gulpfile c:\Users\oca\Desktop\my\gokibitz\gulpfile.js
[13:01:00] Starting 'lint-server-js'...
[13:01:01] Starting 'sass-includes'...
[13:01:01] Finished 'sass-includes' after 932 µs
[13:01:01] Starting 'sass'...
[13:01:01] Starting 'browserify'...
[13:01:01] Bundling app.js...
[13:01:01] Starting 'fonts'...
[13:01:01] Starting 'js-assets'...
[13:01:01] Starting 'images'...
[13:01:01] Starting 'bootstrap-assets'...
[13:01:01] Finished 'bootstrap-assets' after 21 ms
[13:01:01] Finished 'js-assets' after 359 ms
[13:01:02] [gulp-sass] c:\Users\oca\Desktop\my\gokibitz\client\src\scss/rules/mo
dules/_notifications.scss:56: error: unbound variable $font-body

[13:01:02] Finished 'sass' after 1.09 s
[13:01:03] Finished 'lint-server-js' after 2.34 s
[13:01:15] Bundled app.js in 15 s
[13:01:15] Finished 'browserify' after 15 s
[13:01:15] Starting 'uglify'...
[13:01:15] 'Unminified' app.js 2.07 MB
[13:01:27] Finished 'fonts' after 27 s
[13:01:53] 'Unminified' modernizr.js 8.59 kB
[13:01:53] 'Unminified' all files 2.08 MB
[13:01:53] 'Minified' app.js 523.08 kB
[13:01:53] 'Minified' modernizr.js 8.22 kB
[13:01:54] 'Minified' all files 531.3 kB
[13:01:54] 'Compressed' app.js 163.01 kB (gzipped)
[13:01:54] 'Compressed' modernizr.js 3.63 kB (gzipped)
[13:01:54] 'Compressed' all files 166.63 kB (gzipped)
[13:01:54] Finished 'uglify' after 38 s
[13:01:54] gulp-imagemin: Minified 0 images
[13:01:54] Finished 'images' after 53 s
[13:01:54] Starting 'default'...
[13:01:54] Finished 'default' after 120 µs

**Comment by git-oca** [comment]
oups, I did the link 'gokibitz\client\src\scss\lib_gokibitz.scss' to the wrong file...
so I did the link again and now everything is just fine !


C:\Users\oca\Desktop\my\gokibitz\client\src\scss\lib>mklink _gokibitz.scss C:\Us
ers\oca\Desktop\my\gokibitz\node_modules\wgo.js\themes\gokibitz\src\scss\gokibit
z.scss
Lien symbolique créé pour _gokibitz.scss <<===>> C:\Users\oca\Desktop\my\gokibit
z\node_modules\wgo.js\themes\gokibitz\src\scss\gokibitz.scss

**Comment by neagle** [comment]
Ah, I should have anticipated the sym link problem. I wonder if there's a
way to fix it so the sym links will work for Windows users without any
intervention. If not, I should flag this in the documentation.

--
Nate Eagle

On Jan 19, 2015, at 7:52 AM, git-oca <notifications@github.com> wrote:

Closed #17 <https://github.com/neagle/gokibitz/issues/17>.

—
Reply to this email directly or view it on GitHub
<https://github.com/neagle/gokibitz/issues/17#event-220949604>.

**Comment by git-oca** [comment]
I suppose we can handle that in the gulp file,maybe something with fs.lstat and then call stats.isSymbolicLink(), if it's not a symbolic link, we just delete the file and create the symbolic link... I will check that tomorrow and let you know if I can do something here.

**Comment by git-oca** [comment]
Hi,

This 'fix-link' task works well for me : 

gulp.task('default', [
	'fix-link',
	'lint-server-js',
	'sass',
	'uglify',
	'fonts',
	'js-assets',
	'images',
	'bootstrap-assets'
], function () {
	// Nothing!
});

// On windows, symbolic links need to be reconstructed after the project is cloned from git.
gulp.task('fix-link', [], function () {
	if (! fs.lstatSync('./client/src/js/lib/wgo').isSymbolicLink()) {
		fs.unlinkSync('./client/src/js/lib/wgo');
		fs.symlinkSync(
			__dirname + '/node_modules/wgo.js/wgo', // full path requiered on windows
			'./client/src/js/lib/wgo', 
			'dir'
		);
	} 
	if (! fs.lstatSync('./client/src/scss/lib/_gokibitz.scss').isSymbolicLink()) {
		fs.unlinkSync('./client/src/scss/lib/_gokibitz.scss');
		fs.symlinkSync(
			__dirname + '/node_modules/wgo.js/themes/gokibitz/src/scss/gokibitz.scss', // full path requiered on windows
			'./client/src/scss/lib/_gokibitz.scss', 
			'file'
		);
	}
});

but I don't know if it will conflict with the 'link-wgo' task which is also present in the gulpfile to handle specific build config.

**Comment by git-oca** [comment]
Another point that need modification on the windows platforme is that the package.json file nedd to be modified like that :

  "scripts": {
    "start": "node ./server/bin/www"
  },

instead of the current "start": "export $(cat .env | xargs) && node ./server/bin/www"

This is because the "export" command is not present on windows (and unfortunatly, using the git-bash shell doesn't help here...).

**Comment by neagle** [comment]
Thanks for the code for the gulp task for symlinks, @git-oca. Could you try pulling this most recent commit and seeing if the `gulp symlink` task works for you? I rewrote it slightly (I'm in the process of refactoring the gulpfile to use separate task files) but I basically used your code.

RE: the nodemon issue, I don't think that's windows-specific. @LevelOneDev had that issue, and it was related to a break in the most recent version of nodemon. I think Remy Sharp (nodemon's creator) created a fix sometime this morning... let me get back to you.

**Comment by neagle** [comment]
Hmmm, maybe I was wrong about the source of your problem. I've updated the `package.json` file to remove the export command (which I'm embarrassed to say I'm not even sure was doing anything). We'll see if anything blows up.

**Comment by git-oca** [comment]
oups, that didn't worked...

here is what a version of symlink.js that works for me :

var gulp = require('gulp');
var fs = require('fs');
var chalk = require('chalk');

// On windows, symbolic links need to be reconstructed after the project is cloned from git
// Thanks to oca for this code!
gulp.task('symlink', [], function () {
	var symlinks = [
		{
			src: __dirname + '/../../node_modules/wgo.js/wgo',
			dest: './client/src/js/lib/wgo',
			type: 'dir'
		},
		{
			src: __dirname + '/../../node_modules/wgo.js/themes/gokibitz/src/scss/gokibitz.scss',
			dest: './client/src/scss/lib/_gokibitz.scss',
			type: 'file'
		}
	];

	symlinks.forEach(function (symlink) {
		var exists = fs.existsSync(symlink.dest);
		var isSymlink;

		if (exists) {
			isSymlink = fs.lstatSync(symlink.dest).isSymbolicLink();
		}
		// we want to create the link if 
		// - the file doesn't exists at all... (which may occur if gulp is started on windows without adminstrator privilege and the file get deleted but the link is not created.
		// - the file exists, but is not a link...
		if ((!exists) || (!isSymlink)) {
		
			if (exists) {
				fs.unlink(symlink.dest);
			}
			console.log('Creating symlink: ' + chalk.yellow(symlink.src) + ' → ' + chalk.green(symlink.dest));

			fs.symlinkSync(symlink.src, symlink.dest, symlink.type);
		}
	});
});


I have also got a new error :

[20:12:54] gulp-notify: [Compile Error] Error: Cannot find module 'angular-file-
upload' from 'F:\documents\Olivier\jeux\go\dev\gokibitz\client\src\js'
