### ISSUE TITLE
Bug - ranks for imported games from OGS URL

### ISSUE THREAD

**Issue by lVathan** [neagle/gokibitz#174]
Uploaded a game from OGS, and it brought in the wrong ranks.

https://online-go.com/game/11683142

**Comment by neagle** [comment]
This is the most unexpected bug report I've had in ages. The uploaded-to-GoKibitz game is this one? https://gokibitz.com/kifu/SyEddXQwG

**Comment by neagle** [comment]
It looks like the bug is on OGS's side. If you look at the text of the SGF download, it does indeed list black's rank as 6k and white's rank as 7k.

I'd recommend opening a bug with OGS. If I can help provide any further context or information, let me know! (Look at the BR and WR properties.)

```
(;FF[4]
GM[1]
DT[2018-02-15]
PC[OGS: http://online-go.com/game/11683142]
PB[nc88]
PW[power.real]
BR[6k]
WR[7k]
CP[online-go.com]
RE[B+R]
SZ[19]
KM[6.5]
RU[japanese]
C[power.real: hi
nc88: hi
]
;B[pc]
C[nc88: hi
]
```
