### ISSUE TITLE
kifu snapshot generation seems to be broken

### ISSUE THREAD

**Issue by alexmitrani** [neagle/gokibitz#185]
gokibitz until recently generated very nice snapshots of kifus when links to games were posted in other places such as Discord, Whatsapp, and Twitter.  This is no longer happening and I miss it.  I think other people miss it too, we make extensive use of gokibitz at openstudyroom.org.   It would be great if this could be fixed.  Many thanks!

**Comment by neagle** [comment]
Thanks for flagging this: I recently had to renew my SSL certificate, and I missed a step that made the preview images no longer get picked up. I'm very gratified to know that someone else values those preview images: they were something that I always wanted that I only got around to adding a couple of years ago.

They should be working now—let me know if you have further issues.

**Comment by alexmitrani** [comment]
thanks very much for fixing it so quickly!

**Comment by alexmitrani** [comment]
it seems to be broken again.  tested with this link: https://gokibitz.com/kifu/BkgQ8KpY4?path=328

**Comment by neagle** [comment]
Hey, @alexmitrani! It looks like there's a particular issue with that game record. If you back to [the beginning](https://gokibitz.com/api/kifu/image/BkgQ8KpY4/1), it works. It actually doesn't break right up through [move 321](https://gokibitz.com/api/kifu/image/BkgQ8KpY4/321), at which point white passes, and then black moves again. I think this is a previously undiscovered bug in my SGF parser. I'll see if I can look at it this weekend. In the meantime, snapshots should still be working for most other cases.
