### ISSUE TITLE
gokibitz seems to be offline

### ISSUE THREAD

**Issue by alexmitrani** [neagle/gokibitz#189]
I get the following message: 

502 Bad Gateway
nginx/1.10.3 (Ubuntu)

Hope to see it back online soon.

Thanks

Alex

**Comment by neagle** [comment]
Thank you, Alex! I was able to log on and get things restarted thank to your note. I appreciate it!

**Comment by alexmitrani** [comment]
No problem, thanks for getting it back online so quickly.
