### ISSUE TITLE
gokibitz seems to be down

### ISSUE THREAD

**Issue by alexmitrani** [neagle/gokibitz#190]
https://downforeveryoneorjustme.com/gokibitz.com

502 Bad Gateway
nginx/1.10.3 (Ubuntu)

thanks

**Comment by neagle** [comment]
Thanks, as always, for the notification. This was an unplanned server restart. There's some issue that's preventing GoKibitz from restarting automatically on its own when its host restarts; it's gone unfixed for a long time because the server's been quite stable, but maybe the urgency is going up.
