### ISSUE TITLE
'kifu' page hangs indefinitely

### ISSUE THREAD

**Issue by popz73** [neagle/gokibitz#197]
hi neagle, 
something isn't right.. the 'kifu' page (that usually lists everyone's uploaded games) spikes up in cpu/ram usage and doesn't display anything

![image](https://user-images.githubusercontent.com/12851952/69000231-a8689c00-08cc-11ea-992a-5c039439525d.png)

Cheers,
Joao

**Comment by alexmitrani** [comment]
I'm also getting this issue :-(

**Comment by neagle** [comment]
There’s probably an issue with a Kifu uploaded today. I’m out of the house for at least a few more hours, but I’ll check things out as soon as so get home.

--
Nate Eagle

**Comment by alexmitrani** [comment]
It seems to be working now on chrome for Android.

**Comment by neagle** [comment]
I just got things working; it's a similar issue to one that popped up for another user recently. There's a way of getting a malformed SGF uploaded that seems to cause GoKibitz's SGF parser to self-destruct. This time there were three of them, all uploaded by the same user (clearly accidentally). Thanks for notifying me of this and sorry for the outage: it was tough to figure out. I'm going to work on finding a way to prevent this.
