### ISSUE TITLE
Feature Request - Click to name intersection

### ISSUE THREAD

**Issue by foebea** [neagle/gokibitz#20]
Clicking on the board would insert into comment area the selected intersection.

**Comment by neagle** [comment]
Definitely planning on doing this. It's a pain to have to consciously
figure out the intersection coordinates, move by move.

**Comment by neagle** [comment]
Just launched this tonight: I hope it addresses this issue for you. :)

![interactive variations](https://cloud.githubusercontent.com/assets/176993/5952233/d50f00ca-a740-11e4-9346-3dc497995c72.gif)

**Comment by git-oca** [comment]
Thank you very much, This is so cool !
I LIKE IT 
I LIKE IT 
I LIKE IT

**Comment by neagle** [comment]
Best comment to wake up to ever <3

--
Nate Eagle

On Jan 29, 2015, at 12:47 AM, git-oca <notifications@github.com> wrote:

Thank you very much, This is so cool !
I LIKE IT
I LIKE IT
I LIKE IT

—
Reply to this email directly or view it on GitHub
<https://github.com/neagle/gokibitz/issues/20#issuecomment-71972425>.

**Comment by foebea** [comment]
You do good work. Thanks much!
