### ISSUE TITLE
Bug: Player ranks display incorrectly

### ISSUE THREAD

**Issue by ksafford** [neagle/gokibitz#202]
The last few kifu I have uploaded list the ranks of the players incorrectly. Examples here:

https://gokibitz.com/kifu/BkhQZvucL
https://gokibitz.com/kifu/ByFmT-sKU
https://gokibitz.com/kifu/S1BgQLsOI

Historically, this did not happen. e.g. 
https://gokibitz.com/kifu/Sk_JMP8O8

I am simply downloading the sgf files from OGS without modifying their content. This appears to happen whether or not I alter the file name.

**Comment by neagle** [comment]
Looks like this is a bug with OGS. If I download the SGF directly from OGS, the player ranks are the incorrect ones displayed on GoKibitz:

```
BR[19k]
WR[21k]
```

(You can pop open the SGF file with a text editor and check it out yourself. Here's [an index of properties](https://www.red-bean.com/sgf/proplist_ff.html) for SGF files.)

Hopefully OGS can take care of the problem if you submit an issue with them. Good luck!
