### ISSUE TITLE
Bug: unable to login

### ISSUE THREAD

**Issue by bani** [neagle/gokibitz#210]
I've been trying to login for a few days and it hasn't been working.

In the UI nothing happens. Looking at the developer console, I get the following:
```
POST https://gokibitz.com/auth/session [HTTP/1.1 400 Bad Request 63ms]
Request: {"provider":"password","password":"[redacted]"}
Response: "Missing credentials"
```

**Comment by neagle** [comment]
Hi Vanessa,

I'm very sorry to hear you're having trouble logging in. GoKibitz is mostly in maintenance mode and running steadily and reliably on its own these days. I just checked the site and tried to log in with two different accounts and didn't have any issues. I also see other activity still going on.

1. What browser are you using?
2. Can you try going into incognito / private browsing mode and logging in?
3. If you're still having problems, can you try creating a new account and seeing if you're able to log in?

**Comment by bani** [comment]
Sorry, my bad. Login is working.

**Comment by neagle** [comment]
Glad you got things sorted!

--
Nate Eagle
