### ISSUE TITLE
feature request: Comments as list

### ISSUE THREAD

**Issue by csessh** [neagle/gokibitz#214]
Similar to clicking on the notification button to get a list of comments, it would be nice to be able to navigate comments in a game.
Comment navigation in game is very restricted at the moment: clicking arrow buttons multiple times

**Comment by neagle** [comment]
GoKibitz isn't really possible to develop right now (just getting the dependencies up-to-date enough to release new versions would be a considerable task), but there actually is a kinda secret way to navigate between comments. At any place on GoKibitz, you can hold down ? to see a help menu. And that help menu shows that when viewing a game record, you can use alt + left or right arrow to navigate between moves that have comments on them.

Maybe that'll help a little bit!
