### ISSUE TITLE
Can't sign up or log in through mobile interface

### ISSUE THREAD

**Issue by neagle** [neagle/gokibitz#24]
can't sign up through mobile interface. Unable to write on any field... cursor disappears when clicking anywhere.

**Comment by neagle** [comment]
Looks like this was an issue with Angular Bootstrap, a library I use to provide Bootstrap JS widgets as Angular directives for my very Angular-driven web app.

angular-ui/bootstrap/issues/2280

They've got a fix in the master branch, so I downloaded and built the prelease version, and that seems to fix the problem. I'll swap in the official release when 0.13 comes out.

**Comment by git-oca** [comment]
Cool, I also had somehow that problem... but fighting a bit against the iphone I always endup with the cursor in the right field... and go is about fighting is it ?  ;)

**Comment by neagle** [comment]
Haha: that's what Steve Krug calls a kayaking problem. One users are able
to recover from. (Or, in this case, _extremely dedicated_ users.)
