### ISSUE TITLE
Automatic PNG generation

### ISSUE THREAD

**Issue by neagle** [neagle/gokibitz#26]
It would be nice to automatically generate PNGs for images in Twitter/Facebook links, etc. from board positions.

**Comment by levelonedev** [comment]
Would we want to implement twitter cards whatever the facebook equivalent is? 
https://dev.twitter.com/cards/overview

It also seems easy enough to make a PNG of what WGo.js renders.
http://stackoverflow.com/questions/923885/capture-html-canvas-as-gif-jpg-png-pdf

**Comment by neagle** [comment]
Yes! For Facebook, it's mainly `og:image`: `<meta property="og:image"
content="http://graphics.myfavnews.com/images/logo-100x100.jpg" />` (ref: https://developers.facebook.com/docs/sharing/best-practices), but implementing twitter cards would be great, too.

I didn't realize it was quite that easy to generate a png from a `canvas` element. It'll still be a little tricky to generate it from WGo.js, though, as WGo.js is actually a layered stack of canvas elements:

![2015-06-02 at 11 21 am](https://cloud.githubusercontent.com/assets/176993/7939549/9cf41b2c-0919-11e5-9246-c284ba100dd9.png)

**Comment by neagle** [comment]
Finally got this wishlist item done!

![image](https://cloud.githubusercontent.com/assets/176993/21828868/ed4328ea-d760-11e6-879b-117ab895814b.png)

It's a small thing, in a way, but I think it makes sharing games a lot cooler.

It required creating a specific png-generation service in the API. So you can now get [a png version of any move in an uploaded game](https://gokibitz.com/api/kifu/image/BJBlm4W8g/48)... and that includes variations. This might be useful for other stuff down the road.

The renderer does have some limitations: it only really handles white and black moves, and if the SGF does fancier stuff like erase points or anything, it just stops and renders what it had up to that point.
