### ISSUE TITLE
Coordinates not visible on board in Iceweasel

### ISSUE THREAD

**Issue by xcombelle** [neagle/gokibitz#29]

**Comment by neagle** [comment]
Could you tell me more about what you mean? We've got coordinates on the sides...
![2015-01-27 at 10 05 am](https://cloud.githubusercontent.com/assets/176993/5920642/18515986-a60c-11e4-850b-6bca94138f69.png)

Do you mean something like this (forgive the three-second rendering), where there'd be a tooltip or something similar next to your mouse to show you what coordinate you're over?
![2015-01-27 at 10 05 am](https://cloud.githubusercontent.com/assets/176993/5920668/498cbd1a-a60c-11e4-91c3-496fdc5ebaa7.png)

**Comment by xcombelle** [comment]
It's the first thing. So it's a bug. I'm under iceweseal 35.0 (approx firefox 35.0) and it doesn't show the coordinates

![test](https://cloud.githubusercontent.com/assets/69212/5925039/0a0fa08a-a661-11e4-9958-6536184363bb.png)

**Comment by neagle** [comment]
Ah, that clarifies things. Hmm... in Firefox 34.0.5 the coordinates seem fine.

Could you do me a favor and [go to this WGo.js demo](http://wgo.waltheri.net/demo/player/1) and try turning coordinates on?

![2015-01-27 at 2 29 pm](https://cloud.githubusercontent.com/assets/176993/5925358/fe27a220-a630-11e4-9be7-9c31c60facc0.png)

I'm guessing it's an issue for WGo generally, in which case we might do best lodging a support ticket with him.

**Comment by xcombelle** [comment]
On wgo site it works correctly. I saw there is however some part of stylesheet which generate error under my browser I paste in in a gist https://gist.github.com/xcombelle/9098617da9710f91c796

**Comment by neagle** [comment]
Closed by https://github.com/neagle/gokibitz/commit/22c00d980985d4ae8fc7a495600e8047aa0271e7

Thanks to @xcombelle for reporting this, and ENORMOUS thanks to @levelonedev for tracking down and fixing this issue.

**Comment by xcombelle** [comment]
Thanks @neagle and @levelonedev it was the only thing that I missed to be perfectly happy
