### ISSUE TITLE
add an "email" type to the login input field

### ISSUE THREAD

**Issue by git-oca** [neagle/gokibitz#34]
Add an "email" type to the login input field, so that on mobile devices, the keyboard while directly show the @ character.

**Comment by neagle** [comment]
I think I managed to fix this one in record time: four days ago! ;) I noticed the same issue earlier this week, and pushed out a fix a little bit ago.

https://github.com/neagle/gokibitz/commit/3475332a5fefdea60af49beddfa939970324ab52

Also: I can't say enough how useful issue reports like this are to me. Thanks!

**Comment by git-oca** [comment]
oh... great thank you ! I just tried and that works fine for me !
