### ISSUE TITLE
Upload from smartgo for iPad.

### ISSUE THREAD

**Issue by levelonedev** [neagle/gokibitz#52]
I want to be able to upload some of the games I have recorded in person from my iPad. When I visit the site, I don't know how to select anything to upload other than photos. 

I can however paste the SGF contents from smartgo. 

Maybe I am just a bad iPad user but I don't think it is a bad idea either way to have a textbox for pasting in games.  (I'm sure design wise that sounds ugly though).

**Comment by neagle** [comment]
This is something I was thinking about this weekend, too. I'll add a textbox for pasting, definitely.
