### ISSUE TITLE
Feature Request -> Mention user in a comment

### ISSUE THREAD

**Issue by lukas1** [neagle/gokibitz#59]
As a user I want to be able to mention other users in comment, so that when I mention them, they get a notification about it and can respond to my comments. "Mention" functionality should follow conventional syntax: @user

Autocomplete for this feature would be nice UX.

**Comment by neagle** [comment]
I've thought about this too and I definitely agree that it's a good idea. There's a bit of work involved, so I can't promise when I'll get to it, but it's good to have this added to the to-dos.

--
Nate Eagle

**Comment by neagle** [comment]
@levelonedev I just pushed a refactor of `gkCommentBox` that removes the isolated scope and still works for game comments, comment edits, and the primary comment box. Hopefully this will help you more than it messes you up by creating a change with a file you're working on. https://github.com/neagle/gokibitz/commit/fa352cbd18cf5c0198e4ed2de4eb771eed8d5766
