### ISSUE TITLE
Feature Request - Seeing what server games where played

### ISSUE THREAD

**Issue by V1rtu4l** [neagle/gokibitz#61]
Feature Request - Seeing what server games where played, or and maybe a textfield to add where they were played, ie on a tournament. In the main Kifu list, maybe besides the date? Just a suggestion though!

**Comment by neagle** [comment]
Yeah, I have a branch with some initial work for displaying a lot more of the SGF's information, including the server (well, kind of: it roughly coincides with the [AP](http://www.red-bean.com/sgf/properties.html#AP) property). There's also [a specific info property](http://www.red-bean.com/sgf/properties.html#PC) for displaying the place a game was played. Hopefully I can launch that soonish.

**Comment by neagle** [comment]
Added today! f835141a29d71b4bda7a70b8b3e3227d227dcc81
