### ISSUE TITLE
Board Orientation / Rotation

### ISSUE THREAD

**Issue by bigblindbais** [neagle/gokibitz#68]
When I submit a game, the board will not have the same orientation that it had when I played it, and this really screws up with my memory of how the game went (and I guess other people's as well), and I find it very hard to comment on my thought process during the game. Would be great if there were a way to rotate the board.

(thanks for the service, it's a cool website)

**Comment by neagle** [comment]
First of all, welcome to GoKibitz!

Your request is pretty interesting: this has never come up for me because on KGS, where I play almost all of my online games, both players see the board the same way. In other words, it doesn't try to have one side up for one player, and the other side up for the other player as if they were sitting across a real board. That's not realistic, exactly, but it makes for easier review because there's no difference in orientation.

Now, I have _no_ idea why PandaNet would have the record rotated 90º: that's crazy.

If I did add the ability to rotate the board, the coordinates would need to rotate with it, since the coordinates need to stay the same for all users to make commenting possible. I could do something as simple as this:

![2015-04-28 at 9 50 am](https://cloud.githubusercontent.com/assets/176993/7371096/95504f2e-ed8c-11e4-944f-2b78b299d7d6.png)

Where I just use CSS to rotate the whole board and not change anything else about how it works. (For instance, the letters and numbers of the coordinates are sideways.) That's doable, though I'd have to think about how to add interface elements to make it possible.

For something more advanced, I'm not sure it would be worth the work involved at this point, given that this is only a problem on one client (so far).

Would the simple option work for you?

**Comment by bigblindbais** [comment]
Hi Nate, thanks for the lightning speed reply! shows your commitment to this project.

At first I thought that being able to rotate the board was an ok solution; but then I realized that this will create more problems; for example when people comment general areas rather than specific points, they use words like "top", "bottom", etc.. and again perspective becomes a burden.

I think the cleanest solution, if possible, would be to rotate your internal representation (whatever you're using) directly when loading the kifu specifically from PandaNet/IGS; then no rotation is needed. I tried looking through your source to see if that is possible, but couldn't find the related code yet.

**Comment by neagle** [comment]
If there's one correct rotation that's different from the SGF itself, then,
yeah, we could do some initial processing to do that on upload. I'd need to
understand the problem a little better, though: when you get it from
PandaGo, is it wrongly rotated for both players? I can try to investigate
this, too. PandaNet has by far the weirdest SGF issues. :P

Also: if you're a developer, forgive me for noting that I definitely
welcome pull requests and collaboration. ;D

**Comment by bigblindbais** [comment]
I've read a comment by my opponent that said that he also saw the game from the wrong perspective. But I have to make sure that it was the same, because I have the vague feeling that the game is actually shown from two different perspectives on that client (in which case, unfortunately, only a dynamic rotation setting would help). I'll get back to you as soon as I confirm this.

I'm a programmer but not a web-developer, so I can try to see if I can hack something but I can't promise anything :P

**Comment by bigblindbais** [comment]
Ok I've figured out what the problem is.

Luckily both players do see the game from the same perspective. Weirdly enough, the problem is not a rotation, but a reflection! Basically the left and the right of the board are correct, but the top and bottom are not, i.e. the row indices are inverted. I think the best solution to this is to adjust the board upon loading the kifu.

**Comment by neagle** [comment]
It's pretty weird that they reflect the game either in the client or when writing to the SGF.

Writing a bit of code to perform a coordinate reflection for SGFs from PandaNet when they're uploaded isn't too difficult, but we should document the verification steps to make sure this is consistent behavior and won't cause any problems of its own.

**Comment by git-oca** [comment]
Hello,
This is very weird, every game I upload comes from panda-net and they appear in the right way without rotation or reflexion. I usually download the sgf from "netSocialPlaza" on panda-net by clicking on the sgf link in the game history section.

Then I manualy replace the tag CoPyright by CP in the sgf and then everything is fine when I import the game here....

**Comment by bigblindbais** [comment]
I confirm, through manual inspection, that the SGF files obtained by the client and by the netSocialPlaza platform are different (e.g. the latter contains the comments, while the former does not), and that the moves in the SGF files obtained by the client are reflected, as previously described. I'll try to get this to the attention to the developers.

git-oca, any particular reason you replace the CoPyright tag?

**Comment by git-oca** [comment]
Hi bigblindbais,

The CoPyright tag was not supported by wgo.js which only support two letter tags. 
If not changed, the other properties after the CoPyright were not read correctly so my first posted game ended up with two anonymous players

But maybe this is fixed by now...

**Comment by neagle** [comment]
Sadly not. You know, though, now that you bring it up, I could filter this
out on my end so that WGo.js didn't have to deal with it.

**Comment by git-oca** [comment]
> I could filter this out on my end so that WGo.js didn't have to deal with it.

Sure !  That would be nice !

**Comment by neagle** [comment]
@bigblindbais If there is a clear way to distinguish between the correct SGF and the incorrectly reflected one, I'd still be open to manually fixing it on upload, though it'd definitely be better (and easy for me) to get this fixed [by PandaNet's devs](http://pandanet-igs.com/communities/gopanda2). There was just [a reddit post](http://www.reddit.com/r/baduk/comments/342acj/how_can_i_get_your_viewership_for_online/) by someone from IGS soliciting bug reports, so it might not fall on deaf ears.

> You can help us by reporting bugs, crashes and unexpected behavior. Please describe what you were doing when the bug occured and what exactly happend, including the error message generated by the client.

> Please contact us at: gopanda2@pandanet-igs.com

In the meantime, I'll close this post, but you can still comment on it, so let me know if you get any updates.

@git-oca I'll make a new ticket for that.

**Comment by bigblindbais** [comment]
Well I did contact them a few days ago about this, but I still didn't receive any reply. I guess it still makes sense to wait some more though.

**Comment by neagle** [comment]
That sucks that they haven't gotten back to you. You might give them a bit longer: I can imagine they're busy. Keep me updated.
