### ISSUE TITLE
Game commentary as uploader: only the last one remains

### ISSUE THREAD

**Issue by sphaso** [neagle/gokibitz#69]
Heya, I've found a pretty interesting bug:
- upload a game (in my case: http://gokibitz.com/kifu/Nk2F2p_G )
- pick a random move and comment on it (as "Game comments", not kibitz comments)
- do the same on any successive move (I haven't tested on preceding moves)
- go on the Kifu page and go back to your game
- only the last comment remains!

I tried to investigate a bit and I see the PUT requests being performed. They return an empty array as "comments" but I'm not sure if it's relevant or not.

I was able to reproduce this a couple of times. Should it help I'm using Firefox.

**Comment by neagle** [comment]
Great bug identification! I *hate* that there are issues with the game
comment thing, since it's super frustrating to take the time to craft some
text and have it be lost. I'll check into this tonight.

**Comment by neagle** [comment]
This was a pretty dumb oversight on my part, but because I kept testing on single moves, I didn't notice throughout my development. That's why I really appreciate your taking the time to report this. :)

**Comment by neagle** [comment]
This is fixed and launched on live. Make sure you reload the page to get the refreshed JS, and you should be good to go.

**Comment by sphaso** [comment]
Wow thanks for the quick fix :)

**Comment by neagle** [comment]
Least I could do: that was an ugly bug, and you not only reported it but had its behavior accurately and precisely described for me. Thank you again!
