### ISSUE TITLE
Need account recovery mechanism

### ISSUE THREAD

**Issue by dstockwell** [neagle/gokibitz#71]
eg. email with verification code.

I've already forgotten my password :P

**Comment by neagle** [comment]
Drat, I'm really going to have to do this incredibly essential bit of work, aren't I? Okay: this is my top priority. :)

--
Nate Eagle

**Comment by neagle** [comment]
Just an update: I got the first part of this done last night. Hope to have something for you soon.

**Comment by dstockwell** [comment]
ping :P

**Comment by neagle** [comment]
Quite a justified ping! I got the first part of this done quickly, then got considerably delayed. :smile: Thanks for prompting this back to the top. I _will_ try to get this done asap: as I mentioned, I'm pretty close.

In the meantime, would you like to pursue an intermediate solution for you? I'm not sure how many comments or games you have uploaded, but if so, we could recreate your account and I could do a db rewrite to switch them over. We definitely need the feature you requested, but it sucks to make you wait.

**Comment by renanpablocruz** [comment]
any news?

**Comment by neagle** [comment]
It's been a long time, but I've finally shifted things round to do active development on GoKibitz, and this was basically the top of my list. It's now possible to reset your password.

![image](https://cloud.githubusercontent.com/assets/176993/21467574/878c649c-c9c0-11e6-9a25-51bce3154825.png)
