### ISSUE TITLE
Filter out the CoPyright property for WGo.js

### ISSUE THREAD

**Issue by neagle** [neagle/gokibitz#72]
It breaks IGS uploads and @git-oca's been having to do it manually.

**Comment by neagle** [comment]
The simplest way of dealing this turned out to be adjusting the regular expression WGo.js used to parse property IDs to accept lowercase letters. On a relatively casual inspection, it looks like WGo still parses everything correctly, but it no longer chokes on CoPyright.

41241cf83b20e03519a8bad9fd51c46356e29ab9

Let me know if you spot any funny side-effects!

**Comment by git-oca** [comment]
Cool ! I just upload that game http://gokibitz.com/kifu/4k7nqNXm without doing any modification and that worked just fine !
Thanks a lot for making things easier for us even when the problem is not in your application !

**Comment by neagle** [comment]
No problem! And thanks, as always, for helping make GoKibitz better. :) I
really appreciate it!
