### ISSUE TITLE
 Login Case sensitive?

### ISSUE THREAD

**Issue by Eyecatcher00** [neagle/gokibitz#8]
somehow not cool: when i log in it seems that i have to write my email case sensitive  ... i tried "amonbxxxx@gmail.com" but it says: "no email like this" ... but with "Amonbxxx@gmail.com" it worked ... 

not very urgent, but sooner or later i think it would be nice :)

**Comment by neagle** [comment]
Hmm--I guess that should be case insensitive, since emails themselves are. Thanks for pointing this out!

**Comment by neagle** [comment]
Thanks again for submitting this, @Eyecatcher00. This is how it should've been all along.
