### ISSUE TITLE
Filter/Standardize rank display

### ISSUE THREAD

**Issue by neagle** [neagle/gokibitz#82]
![2015-05-11 at 2 39 pm](https://cloud.githubusercontent.com/assets/176993/7572367/8c185b4a-f7eb-11e4-892d-7e8aea0b6f55.png)

Right now, GoKibitz puts an enormous amount of trust in SGFs themselves to contain the correct type of information. The most obvious place this has gone wrong is in rank displays, where one SGF editor uses the word "Pharisee" instead of "kyu" (I'd love to know the story behind that one).

We should filter the information to only display number plus k or d for kyu or dan. Ideally, we can make it friendly enough to transform things like Kyu or kyu into k, and Dan or dan into d, but if it's unparseable, we shouldn't display it.

**Comment by sphaso** [comment]
Are you already working on this? Do you mind if I give it a shot? 
I was thinking that a simple custom filter should do the trick (Pharisee? wot? :D), but there's still the issue of game comments, e.g.:            
```
vegeta [4SuperSayan]: I'm only using 40% of my tsumego knowledge
goku [4SuperSayan]: okie, good game 
```
I guess we cannot really parse that?

**Comment by neagle** [comment]
Go for it! Definitely don't worry about ranks in game comments... That's not a big deal. The main thing is the rank that displays in our UI.

--
Nate Eagle

**Comment by sphaso** [comment]
Is this issue still open because you want to use the filter in other places?

**Comment by neagle** [comment]
Yes, but I guess we could deal with those in separate issues. Thanks for the nudge: closing.
